export type Permission =
  | 'WS_TRANSACTIONS_VIEW'
  | 'WS_TRANSACTIONS_MANAGE'
  | 'DEPOSIT_CASH'
  | 'DEPOSIT_CHECK'
  | 'WITHDRAW_SAVINGS'
  | 'BALANCE_VIEW'
  | 'TRANSFER_OWN'
  | 'TRANSFER_THIRD_PARTY'
  | 'LOAN_BALANCE_VIEW'
  | 'LOAN_PAYMENT_ACCOUNT'
  | 'LOAN_PAYMENT_CASH'
  | 'LOAN_PAYMENT_CHECK'
  | 'LOAN_PAYMENT_REVERSAL';